spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.otp.allow-email-failure=true
app.otp.expose-debug-otp=false
app.otp.return-fallback-otp-on-delivery-failure=false
app.frontend.base-url=${APP_FRONTEND_BASE_URL:https://socialsea.co.in}
spring.jpa.open-in-view=false
