ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS private_account BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS resume_json TEXT;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS resume_updated_at TIMESTAMP;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(16) DEFAULT 'en';

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS notification_voice VARCHAR(16) DEFAULT 'male';

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS vault_lock_json TEXT;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS vault_lock_updated_at TIMESTAMP;
