ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS private_account BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS resume_json TEXT;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS resume_updated_at TIMESTAMP;
